// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

export const environment = {
  production: true,
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  apiUrl: 'http://192.168.1.52:8081/api/v1',
  // clientSecret: 'repairsAdvisorisgoingtothemoonanddropgoldtofoundersBAHthenIcanplaygameallday',
  serverUrl: '/api',
  airwallex: {
    // Demo web app URL: https://demo.airwallex.com/app/login

    apiUrl: 'https://demo.airwallex.com/docs/api',
    clientEmail: 'demo+repairsadvisorllc@airwallex.com',
    clientPassword: 'Abcde1234',
    accountId: '335cfeb5-b6d3-4243-b0fa-1f67b5266bbf',
    clientId: 'E9G_znnUQtuPD16QZlURMw',
    apiKey: 'bfcf765d976521a22337c57d44dd9a65580f7b0acae4617338aa4f2e6178b7a34e73aee762e40d656dc962c64841a44a',
},
};
